project:
  type: website
  output-dir: docs
  
website:
  title: "Aubrey Dissinger"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://x.com/adisseus
      - icon: github
        href: https://github.com/aubreydissinger/aubreydissinger
      - icon: fa-solid fa-fish-fins
        href: https://kwaseklab.github.io/LabWebsiteTest/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, YOUR NAME"

format:
  html:
    theme: cerulean
    toc: true

editor: source

